language: cpp
compiler:
  - gcc
install:
  - ./build.sh
script:
  - ./build/runtest
notifications:
  recipients:
    - tkoomzaaskz@o2.pl
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.8.7
  - 1.9.3
