language: cpp
compiler:
  - gcc
install:
  - sudo apt-get update
  - sudo apt-get install libcppunit-1.12-1
  - ./build.sh
script:
  - ./build/runtest
notifications:
  recipients:
    - tkoomzaaskz@o2.pl
  email:
    on_success: change
    on_failure: always
